// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Hazzat.iOS
{
	public partial class MainMenuStack : UITableView
	{
		public MainMenuStack (IntPtr handle) : base (handle)
		{
		}
	}
}
